server:
  port: 10013
spring:
  application:
    name: exam-user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/exam_hfr?characterEncoding=utf-8
    username: root
    password: 1234
    hikari:
      max-lifetime: 28830000
      maximum-pool-size: 9
eureka:
  client:
    registry-fetch-interval-seconds: 5 #拉取服务的间隔时间5秒
    service-url:
      defaultZone: http://127.0.0.1:10010/eureka
  instance:
      lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
      lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
mybatis:
  type-aliases-package: com.itdupan.pojo